# Build settings
#markdown: redcarpet
#highlighter: pygments
gems:
  - jemoji
#  - pygments
  - jekyll-paginate
  
# Site settings
title: "Andrew Paradi"
description: > # this means to ignore newlines until "email:"
   Growth Focused Front End Developer

email: me@andrewparadi.com
#blog logo
logo: "/assets/images/ap_logov3.5.png"
# blog cover
cover: "/assets/images/launchpad-c.jpg"

name: 'Andrew Paradi'
author: 'Andrew Paradi'
author_image: "/assets/images/andrew2015.jpg"
bio: "I study computer science at University of Waterloo, enjoy writing on my blog, producing videos, and playing piano."


toggle_menu: True
categories:
  - title:	Projects
    cat:  project
    url:	/
    desc:	"Volunteer work, hackathon hacks, freelance work, and summer internship projects."
    
  - title:	Work
    cat:  work
    url:	/work/
    desc:	"Work experience from summer internships to managing a team of 5 at my startup."

  - title:	Blog
    cat:  blog
    url:	/blog/
    desc:	"Book reviews, startup thoughts, and case studies diving deep into how a project ended up being successful."
    
paginate: Nil

url: "//andrewparadi.com" # the base hostname & protocol for your site
baseurl: ""
enforce_ssl:
permalink: /:categories/:title/
#used to display twitter cards
twitter_handle: '@andrew_paradi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:

  - icon:	inbox
    url:	mailto:me@andrewparadi.com
    desc:	Email me@andrewparadi.com
    share_url:
    share_title:
    share_link:
    caption:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/andrewparadi
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
    caption:
    
  - icon:	github
    url:	https://github.com/andrewparadi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    caption:

  - icon:	twitter
    url:	https://twitter.com/andrew_paradi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    caption:
    
  - icon:	instagram
    url:	https://instagram.com/andrewnotes
    desc:	Follow on instagram
    share_url: 
    share_title:
    share_link:
    caption:
    
  - icon:	youtube
    url:	https://youtube.com/c/andrewparadi
    desc:	Watch my videos on Youtube
    share_url: 
    share_title:
    share_link:
    caption:
    
    #     PGP Key
  - icon:	lock
    url:	/assets/files/AndrewParadiPGP.zip
    desc:	PGP Fingerprint and Public Key
    share_url: 
    share_title:
    share_link:
    caption: PGP
    
#     resume
  - icon:	graduation-cap
    url:	/assets/files/AndrewParadiResume.pdf
    desc:	Resume as of Jan 2015
    share_url: 
    share_title:
    share_link:
    caption: Resume
    

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
    


#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:






# Defaults for layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
      author: "Andrew Paradi"
