# Based on https://github.com/dirkfabisch/mediator/ as of Apr 17, 2017

gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
#  - pygments

# Site settings
title: "Andrew Paradi"
description: > # this means to ignore newlines until "email:"
   Full Stack Engineer

email: me@andrewparadi.com
#blog logo
logo: "/assets/images/ap_logov4.0t-100c.png"
float_logo: true
# blog cover
cover: "/assets/images/covers/launchpad-c.jpg"
date_format: "%B %e, %Y" # Jun 8, 2017

name: 'Andrew Paradi'
author: 'Andrew Paradi'
author_image_s: "/assets/images/andrew2015-150c.png"
author_image_m: "/assets/images/andrew2015-300c.png"
author_image_l: "/assets/images/andrew2015-600c.png"
author_image: "/assets/images/andrew2015.jpg"
bio: "I study computer science at University of Waterloo, develop software at Atomic, code hacks like this, produce vids, and play piano."
bio_page: "/about"
bio_work: "/project/atomic"
bio_hack: "/experience#hackathons-side-projects"
bio_project: "/progress-pebble"
bio_post: "/blog/videostream-how-growth-starts-with-great-customer-support"
bio_video: "https://youtu.be/hfbE7sVbz8k?list=PLmu6fQR8i26VzMOSuUikzqRLT4diEE_AA"
bio_piano: "https://youtu.be/VuBCs_t54DY"
bio_insta: "https://www.instagram.com/andrewnotes"
work_title: "software developer"
work_term: "early 2018"
resume: "/assets/files/AndrewParadiResume.pdf"

google_analytics: UA-15052723-11
google_webmaster_tools: O_pv2dcb2u8RFakuUQcH-TwV5lPeBs6aNXZJY5xYiDs

header_menu:
  - title: Experience
    slug: experience
    url: /experience
    icon: road
  - title: Projects
    slug: project
    url: /projects
    icon: file-code-o
  - title: Blog
    slug: blog
    url: /blog
    icon: sticky-note
  - title: About
    slug: about
    url: /about
    icon: id-card
  - title: Contact
    desc: Contact Andrew
    slug: contact
    url: /contact
    icon: envelope
  - title: Resume
    slug: resume
    url: "/assets/files/AndrewParadiResume.pdf"
    icon: graduation-cap

experience_sections:
  - title: Work Experience
    slug: work
  - title: Hackathons & Side Projects
    slug: project
  - title: Volunteer Work
    slug: volunteer

paginate:

url: "//www.andrewparadi.com" # the base hostname & protocol for your site
baseurl: ""
enforce_ssl:
permalink: /:categories/:title
#used to display twitter cards
twitter_handle: '@andrew_paradi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - title: LinkedIn
    icon:	linkedin-square
    url:	https://www.linkedin.com/in/andrewparadi
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
  - title: GitHub
    icon:	github
    url:	https://github.com/andrewparadi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
  - title: Email
    icon:	envelope
    url:	mailto:me@andrewparadi.com
    desc:	Email me@andrewparadi.com
    share_url:
    share_title:
    share_link:
  - title: Devpost
    icon:	code
    url: https://devpost.com/andrewparadi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
  - title: AngelList
    icon:	angellist
    url:	https://angel.co/andrew-paradi
    desc:	Add me on Angel List
    share_url:
    share_title:
    share_link:
  # - title: Twitter
  #   icon:	twitter
  #   url:	https://twitter.com/andrewparadi
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="
  # - title: Instagram
  #   icon:	instagram
  #   url:	https://instagram.com/andrewnotes
  #   desc:	Follow on instagram
  #   share_url:
  #   share_title:
  #   share_link:
  - title: YouTube
    icon:	youtube
    url:	https://youtube.com/c/andrewparadi
    desc:	Watch my videos on Youtube
    share_url:
    share_title:
    share_link:
  - title: PGP
    icon:	lock
    url:	https://keybase.io/andrewparadi
    desc:	Keybase.io PGP Fingerprint &amp; Public Key
    share_url:
    share_title:
    share_link:
  - title: Resume
    icon:	graduation-cap
    url:	/assets/files/AndrewParadiResume.pdf
    desc:	Resume as of Jan 2015
    share_url:
    share_title:
    share_link:

# Defaults for layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ""
      author: "Andrew Paradi"
