# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  - pygments
  
# Site settings
title: "Andrew Paradi"
description: > # this means to ignore newlines until "email:"
   Growth Focused Front End Developer

email: me@andrewparadi.com
#blog logo
logo: "/assets/images/ap_logov3.4.png"
# blog cover
cover: "/assets/images/launchpad-c.jpg"

name: 'Andrew Paradi'
author: 'Andrew Paradi'
author_image: "/assets/images/andrew2015.jpg"
bio: "I study CS at University of Waterloo and want to tackle ambitious projects as an intern this summer 2016. Check out my <a href='/about/'>About</a> page or <a href='/assets/files/AndrewParadiResume.pdf' target='_blank'>Resume</a>) to learn more!"
bio2: "I want to tackle ambitious projects as a summer 2016 intern. Learn more <a href='/about/'>About</a> why I might be a great fit for your team (<a href='/assets/files/AndrewParadiResume.pdf' target='_blank'>resume</a>)"

paginate: 20

url: "//andrewparadi.com" # the base hostname & protocol for your site
baseurl: ""
enforce_ssl:
permalink: /:categories/:title/
#used to display twitter cards
twitter_handle: '@andrew_paradi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:

  - icon:	inbox
    url:	mailto:me@andrewparadi.com
    desc:	Email me@andrewparadi.com
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/andrewparadi
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
    
  - icon:	github
    url:	https://github.com/andrewparadi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
#     resume
  - icon:	graduation-cap
    url:	/assets/files/AndrewParadiResume.pdf
    desc:	Resume as of Dec 2015
    share_url: 
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/andrew_paradi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    
  - icon:	instagram
    url:	https://instagram.com/andrewnotes
    desc:	Follow on instagram
    share_url: 
    share_title:
    share_link:
    
  - icon:	youtube
    url:	https://youtube.com/c/andrewparadi
    desc:	Watch my videos on Youtube
    share_url: 
    share_title:
    share_link:
    
    #     PGP Key
  - icon:	lock
    url:	/assets/files/AndrewParadiPGP.zip
    desc:	PGP Fingerprint and Public Key
    share_url: 
    share_title:
    share_link:
    

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
    


#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:






# Defaults for layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
      author: "Andrew Paradi"